# org: georgedavis
# app: filestoragesecurity-azure-malwaretest
service: filestoragesecurity-azure-malwaretest2

frameworkVersion: "3"
configValidationMode: off

custom:
  defaultStage: dev
  stages:
    dev:
      azure_location: East US
      subscription_id: 52411634-d656-4c1f-b8fa-fc6c70544b0c
      resource_group: filestoragesecurity-azure-malwaretest2
      storage_accounts: azurefssnortheurope,azurefsseastusmalicious
      time_interval_in_hours: 3
    prod:
      azure_location: East US
      subscription_id: 52411634-d656-4c1f-b8fa-fc6c70544b0c
      resource_group: filestoragesecurity-azure-malwaretest
      storage_accounts: azurefssnortheurope,azurefsseastusmalicious
      time_interval_in_hours: 3

provider:
  name: azure
  runtime: python3.8
  stage: ${opt:stage, self:custom.defaultStage}
  location: ${self:custom.stages.${opt:stage, self:custom.defaultStage}.azure_location}
  type: consumption
  subscriptionId: ${self:custom.stages.${opt:stage, self:custom.defaultStage}.subscription_id}
  resourceGroup: ${self:custom.stages.${opt:stage, self:custom.defaultStage}.resource_group}
  environment:
    azure_location: ${self:custom.stages.${opt:stage, self:custom.defaultStage}.azure_location}
    subscription_id: ${self:custom.stages.${opt:stage, self:custom.defaultStage}.subscription_id}
    resource_group: ${self:custom.stages.${opt:stage, self:custom.defaultStage}.resource_group}
    storage_accounts: ${self:custom.stages.${opt:stage, self:custom.defaultStage}.storage_accounts}
  tags:
    BusinessCase: FSS-AzureMalwareTest
    Owner: TrendMicro
    CodeSource: https://github.com/GeorgeDavis-TM/filestoragesecurity-azure-malwaretest.git
  stackTags:
    BusinessCase: FSS-AzureMalwareTest
    Owner: TrendMicro
    CodeSource: https://github.com/GeorgeDavis-TM/filestoragesecurity-azure-malwaretest.git
  os: linux # linux is the only operating system available for python
  # prefix: "sample"  # prefix of generated resource name
  # subscriptionId: A356AC8C-E310-44F4-BF85-C7F29044AF99

functions:
  main:
    handler: filestoragesecurity-azure-malwaretest/handler.main
    description: Scheduled run of File Storage Security Malware Test Tasks
    events:
      - timer: true
        name: scheduled-filestoragesecurity-azure-malwaretest-${opt:stage, self:custom.defaultStage}
        # description: 'Cloud One File Storage Security Hourly Malware Test Schedule'
        # x-azure-settings:
        # schedule: "0 0/${self:custom.stages.${opt:stage, self:custom.defaultStage}.time_interval_in_hours} * * * *"
        schedule: "30 * * * * *"

plugins:
  - serverless-python-requirements
  - serverless-azure-functions

package:
  excludeDevDependencies: false
  patterns:
    - "!env/**"
    - "!.env/**"
    - "!local.settings.json"
    - "!.vscode/**"
    - "!__pycache__/**"
    - "!node_modules/**"
    - "!.python_packages/**"
    - "!.funcignore"
    - "!package.json"
    - "!package-lock.json"
    - "!.gitignore"
    - "!.git/**"
  # - '!exclude-me.py'
  # - '!exclude-me-dir/**'
  #   - include-me.py
  #   - include-me-dir/**
